update blueline, bonito, coral, crosshatch, flame, sargo, sunfish for android 11
AOSPAlliance/android-prepare-vendor pull request #21
Opened 2020-09-15 03:30 UTC by dan-v

2020-09-15 14:16 UTC, chirayudesai requested changes
The good: A lot of removals, and not as many modifications / new additions. Especially for 3, 3a families.
4 and 4a have more changes.

The bad: Some of those removals are actually just moves to `system_ext` which we don't support right now.

It'd be trivial to add it in based on the code we added last year for `product`, but do we want to at this point?

2020-09-15 14:16 UTC, chirayudesai commented on coral/config.json
> -        "product/priv-app/ims/ims.apk",
This is now in system_ext

https://git.rip/dumps/google/flame/-/blob/flame-user-11-RP1A.200720.009-6720564-release-keys/all_files.txt

2020-09-15 14:16 UTC, chirayudesai commented on flame/config.json
> -        "product/lib64/libaptX_encoder.so",
These are also in system_ext now.

2020-09-15 14:16 UTC, chirayudesai commented on flame/config.json
> +        "bin/hw/android.hardware.vibrator-service.cs40l25",
I had to do a double take on this one

2020-09-15 14:19 UTC, chirayudesai commented
Dan, would you mind just diffing
- crosshatch and blueline
- bonito and sargo
- coral and flame
- coral and sunfish

And making sure they're sycned up  / the diff looks sane. For the first three I don't think there really would be any changes.

2020-09-15 14:20 UTC, chirayudesai commented
Note: I didn't exhaustively go through the full thing since the list is a lot bigger, but in general since it's most removals / additions to vendor-skip-files, as long as everything works we should be good.

2020-09-15 17:25 UTC, danielfullmer commented
There are also some differences between the built `vendor/build.prop` and Google's `vendor/build.prop` on `crosshatch` (and likely others):
```diff
diff --git a/upstream/vendor/build.prop b/built/vendor/build.prop
index 9a767f3..5675f99 100644
--- a/upstream/vendor/build.prop
+++ b/built/vendor/build.prop
.....
 #
 # ADDITIONAL VENDOR BUILD PROPERTIES
 #
 ro.build.expect.bootloader=b1c1-0.3-6623201
 ro.build.expect.baseband=g845-00107-200702-B-6648703
+ro.carrier=unknown
+ro.config.notification_sound=OnTheHunt.ogg
+ro.config.alarm_alert=Alarm_Classic.ogg
 ro.apex.updatable=true
 keyguard.no_require_sim=true
 ro.control_privapp_permissions=enforce
@@ -138,15 +141,3 @@ aaudio.hw_burst_min_usec=2000
 ro.bluetooth.a2dp_offload.supported=true
 persist.bluetooth.a2dp_offload.disabled=false
 persist.bluetooth.a2dp_offload.cap=sbc-aac-aptx-aptxhd-ldac
-ro.hardware.vulkan=adreno
-ro.hardware.egl=adreno
-vendor.power.pasr.enabled=true
-ro.boot.vendor.overlay.theme=com.android.internal.systemui.navbar.twobutton
-drm.service.enabled=true
-media.mediadrmservice.enable=true
-ro.com.android.prov_mobiledata=false
-ro.storage_manager.enabled=true
-ro.carrier=unknown
-ro.config.notification_sound=OnTheHunt.ogg
-ro.config.alarm_alert=Alarm_Classic.ogg
```

At the very least, we should probably set `ro.hardware.vulkan` and `ro.hardware.egl` in `PRODUCT_PROPERTY_OVERRIDES` like is done in taimen/walleye

2020-09-16 09:06 UTC, dan-v commented
i took another spin through these devices and added system_ext. i didn't quite get a chance to get to sunfish tonight.
* diff between device pairs is now just the `lib/hw/sensors.<device>.so` and `lib64/hw/sensors.<device>.so`.
* the system_ext diffs for these devices are quite large. i picked up the changes and figured we could pair down.
* i've only validated that crosshatch config boots as it previously did

2020-09-16 22:25 UTC, thestinger commented
Need to deal with the system property differences that are specific to devices but this is a good start.

2020-09-16 22:30 UTC, thestinger commented
> drm.service.enabled=true

This controls whether DRM is supported. It should be up to the OS.

> media.mediadrmservice.enable=true

This controls whether proper secure buffers are supported so that the sandbox can be used. This should probably be enabled by android-prepare-vendor, rather than the OS. It doesn't enable DRM but rather sandboxing it securely if it's enabled.

2020-09-16 22:31 UTC, thestinger commented
Going to file a separate issue about system properties.

2020-09-16 22:35 UTC, thestinger commented
https://github.com/AOSPAlliance/android-prepare-vendor/issues/27

2020-09-16 22:40 UTC, thestinger commented
Going to merge this since it's a lot better than the current state. Can handle any issues as follow-up.

2020-09-16 22:40 UTC, merged